meta-imx: Mask unused keyctl-caam bbappend
Issue: LIN1023-5303 LIN1023-5304

keyctl-caam is not used for WRLinux, mask it to fix below building issue:
ERROR: No recipes in default available for:
meta-imx/meta-bsp/recipes-security/smw/keyctl-caam_git.bbappend

(LOCAL REV: NOT UPSTREAM) - WRLinux specific

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>