meta-imx: Disable wifi features by default
Issue: LINUXEXEC-30633

Bringing in the wifi feature by default will cause compilation problems
ERROR: Nothing RPROVIDES 'nxp-wlan-sdk‘

(LOCAL REV: NOT UPSTREAM) - WRLinux specific

Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>